/* eslint-disable camelcase */
const base = {
  site_name: 'Anna Nogaré',
  site_title: 'Anna Nogaré; Interpretive Design Director & Accessibility Strategist, CPACC',
  site_description: 'Creating meaningful experiences that everyone can enjoy.',
  skiplink_aria_label: 'Skip to main content',
  navigation_aria_label: 'Main navigation',
  menu_dialog_aria_label: 'Menu dialog',
  menu_button_aria_label: 'Toggle menu dialog',
  footer_aria_label: 'Footer navigation',
  badge_about_title: 'Learn more about me',
  badge_contact_title: 'Get in touch!',
  badge_manifesto_title: 'Read Accessibility Manifesto',
  button_resources_title: 'Back to resources',
}

const socials = {
  linkedin: {
    href: 'https://nl.linkedin.com/in/anna-nogar%C3%A8-27948048',
    title: 'LinkedIn',
  },

  behance: {
    href: 'https://www.behance.net/annanogar',
    title: 'Behance',
  },
}

const alts = {
  'misc/anna-dots_1x1': 'Anna Nogaré facing the camera with colorful dot projections on her face and shirt, against a dark background.',
  'misc/anna-leaning-forward_1x1': 'Anna Nogaré leaning forward at a table with sticky notes, listening while a man writes in the background.',
  'misc/crowd-in-museum_1x1': 'A long-exposure shot of a crowd moving down white stone steps in a museum, with vibrant graphic design posters on the wall behind them.',
  'misc/production-silhouette_1x1': 'Dramatic silhouette of a production crew and a wooden ladder against glowing blue and magenta walls.',
  'misc/reviewing-blueprints_1x1': 'Close-up of a designer in a red dress reviewing detailed blueprints in a brightly lit interior.',
  'misc/service-gradient-1_1x1': 'A smooth, fluid abstract gradient of luminous colors. A prominent band of magenta and hot pink sweeps diagonally through the centre, transitioning from bright cyan and purple in the top-left to deep navy blue and dark red in the bottom-right. The lighting gives it a soft, neon glow.',
  'misc/service-gradient-2_1x1': 'An abstract digital gradient composed of bold diagonal color bands. It transitions smoothly from a warm peach-orange in the top-left to soft pink and violet. The bottom-right features a dramatic contrast of deep royal blue, followed by a dark shadow and a final, sharp streak of crimson.',
  'misc/service-gradient-3_1x1': 'A textured abstract gradient with a distinct, grainy, paper-like finish. Bright bands of yellow, orange, red, and pink sweep diagonally across the frame from the bottom-left toward the top-right. This warmth is balanced by a soft expanse of sky blue in the bottom-right.',
  'misc/vintage-telephone_1x1': 'An antique-style telephone with a wooden base and silver metal handset against a dark blue background. (Image copyright: Pawel Czerwinski via Unsplash)',
  'misc/wheelchair-sign_1x1': 'Stylized wheelchair symbol painted on asphalt, with a small bouquet of flowers placed in the figure’s hands. (Image copyright: Robert Harkness via Unsplash)',
  'misc/yall-means-all_1x1': 'Rainbow-striped Pride flag with bold white text reading “Y’all Means All!” hanging inside a window. (Image copyright: Megan Bucknall via Unsplash)',
  'projects/badge-academy/01_2x1': 'Illustration of a diverse group of colourful cartoon characters, including a tall red-haired figure, a girl with braids, an old man with a walker, an old lady with an air balloon, a blue-skinned man and a petite pink-haired woman, gathered together on a dark blue background.',
  'projects/badge-academy/02_1x1': 'A person’s hands holding a smartphone in a red case, displaying the Badge Academy app splash screen with the Dutch Police logo, bold yellow title, and illustrated cast of characters.',
  'projects/badge-academy/03_1x1': 'Smartphone mockup on a dark blue background showing the Badge Academy app splash screen, with the Politie logo at the top, a bold yellow comic-style title, a graduation cap, and the full illustrated cast of characters.',
  'projects/badge-academy/04_2x1': 'Illustration of six colourful cartoon characters of varying ages standing in a row, including a pink figure with a balloon, a green character with a walker, a tall figure in green, and a girl with braids, on a dark blue background.',
  'projects/badge-academy/05_2x1': 'Four smartphone screens showing the Badge Academy app structure: a location hub with Academie, Bureau, and Locker; the Academie sub-menu with first aid, administration, and investigation modules; a Bureau mission schedule with timed tasks; and the Locker screen with collectable badges and equipment.',
  'projects/badge-academy/06_1x1': 'Illustration of a Dutch Politie police car with red and blue markings, surrounded by orange traffic cones on a road with green trees in the background.',
  'projects/badge-academy/07_1x1': 'Badge Academy app logo: bold yellow comic-style lettering with a dark shadow on a blue circle, with the white Police torch-and-shield logo above.',
  'projects/badge-academy/08_2x1': 'Three smartphones showing Badge Academy Bureau content: a video of a police officer at the wheel of a patrol car, a chat-style screen with tips from three instructors in Dutch, and a loading screen with an animated blue police siren.',
  'projects/badge-academy/09_2x1': 'Three smartphones showing the “Schakel het gevaar uit” shooting mini-game, with a landscape intro screen and two portrait screens showing orange and teal illustrated robot-like figures, one holding a weapon.',
  'projects/badge-academy/10_1x1': 'Illustration of a jointed wooden crash-test dummy shrugging with arms spread, standing in front of a blue illustrated police academy building with a football pitch and running track.',
  'projects/badge-academy/11_1x1': 'Illustration of a lanky, sullen teal cartoon character in a white vest and rust-red shorts, standing in a residential street with blue apartment blocks against a magenta circle.',
  'projects/badge-academy/12_2x1': 'Four smartphones showing the “Verleen Eerste Hulp” first-aid mini-game, with an injured illustrated character in various states of distress across the screens and three selectable response items: a first aid kit, a bandage, and a cup at the bottom.',
  'projects/badge-academy/13_2x1': 'Four smartphones showing the “Verdedig jezelf” self-defence mini-game, with a small angry orange cartoon character with wild red hair and a briefcase appearing across all screens in escalating confrontation poses.',
  'projects/badge-academy/14_1x1': 'Illustration of a scowling orange cartoon character with red hair and a briefcase, standing in front of a blue bank building against a green circle on a dark blue background.',
  'projects/badge-academy/15_1x1': 'Illustration of a tall red-haired cartoon character in a green striped jumper opening a blue locker, with a small hand cheerfully waving from inside.',
  'projects/badge-academy/16_2x1': 'Three smartphones showing the Plankgas naar de overval driving mini-game: a comic-style landscape intro screen with the red-haired villain, a top-down street scene with barriers and a stop sign, and a 3D first-person driving view with directional controls.',
  'projects/badge-academy/17_2x1': 'Four smartphones showing the “Wat te doen” decision-making mini-game, featuring a green cartoon character in different scenarios: playing baseball, reporting a burglary, and jaywalking, with three action options at the bottom.',
  'projects/badge-academy/18_1x1': 'Illustration of a small green cartoon character wearing a sports headband and using a walking frame, standing in a dimly lit home interior with a yellow circle in the background.',
  'projects/badge-academy/19_1x1': 'Illustration of a smiling pink cartoon character meditating with eyes closed, holding a colourful striped balloon, with a thought cloud above its head and a boxing ring in the dark blue background.',
  'projects/badge-academy/20_2x1': 'Illustration of three mobile phones showing different screens of a detective game against a blue background. The screens display the Dutch text “Zoek het bewijs!”, a 3D room, and a mini-game featuring a dark blue bottle with a red stain.',
  'projects/badge-academy/21_2x1': 'Illustration of four mobile phones showing a sequence from a running game against a blue background. The screens display the Dutch title “In de achtervolging!” and follow a character with long braids chasing a pink grandmother holding a striped balloon.',
  'projects/badge-academy/22_1x1': 'Illustration of a yellow-skinned cartoon character with long braids, glasses, and red headphones. In the background, a blue bank building stands before a massive textured orange sun against a dark night sky.',
  'projects/badge-academy/23_1x1': 'A stylised monochromatic blue illustration of a dimly lit, messy office room. A baseball bat sits on top of stacked books on a large desk, surrounded by scattered items like a pistol, a bottle, an axe, and a single lit candle.',
  'projects/badge-academy/24_2x1': 'Illustration of three mobile phones displaying a case-sorting game interface against a blue background. The screens feature the Dutch text “Orden het bewijs!” alongside yellow “Top secret” folders containing suspect photos, fingerprints, and evidence.',
  'projects/badge-academy/cover_3x1': 'Close-up of a rain-wet Dutch police (Politie) vest, showing the force’s torch-and-shield logo and yellow reflective stripe across the back.',
  'projects/badge-academy/thumbnail_1x1': 'A person’s hands holding a smartphone in a red case, displaying the Badge Academy app splash screen with the Dutch Police logo, bold yellow title, and illustrated cast of characters.',
  'projects/canon/01_2x1': 'A front view of an open laptop sitting on a white surface against a soft grey-blue backdrop. The screen displays the Canon Professional Network website, showcasing a technical article titled “Flying high: filming an air display with the EOS C700” with a photo of a pilot inside a cockpit.',
  'projects/canon/02_1x1': 'A clean, graphic logo centred on a dark charcoal gradient background. It features the bold, whitestylised acronym “CPN“” with “Canon Professional Network” printed directly underneath in a sans-serif font, accompanied by a distinct red dot on the right side.',
  'projects/canon/03_1x1': 'A Canon mirrorless camera body resting on a rough, textured stone surface outdoors during the warm light of golden hour. The camera lens is removed, clearly exposing the reflective internal image sensor, with a blurred rocky landscape in the background.',
  'projects/canon/04_2x1': 'Three black tablets arranged in a row against a light grey background, displaying consecutive pages of a digital article from the Canon website. The layout highlights fine-art photography, featuring text blocks alongside creative portraits of women in unique settings.',
  'projects/canon/05_2x1': 'Three black tablets side-by-side displaying an online editorial article. The digital pages combine columns of text with documentary photography, including a poignant image of a woman cradling a small child on the left tablet, and a group of white doves in flight on the other screens.',
  'projects/canon/06_1x1': 'A desktop computer monitor showing a webpage under the “Inspiration” section of the Canon Professional Network site. The main focus of the screen is a wide banner image featuring a group of smiling people gathered together outdoors.',
  'projects/canon/07_1x1': 'A desktop monitor displaying a website biography page. The upper half of the screen features a large, horizontal photograph of a woman wearing a patterned headscarf standing on a rocky hillside that overlooks a dense, widespread city below.',
  'projects/canon/08_2x1': 'Three black tablets arranged side-by-side showcasing a multi-page digital profile layout. The pages display a combination of biographical paragraphs and prominent documentary images, including a portrait of a young girl looking out through a rain-streaked glass window.',
  'projects/canon/cover_3x1': 'A close-up shot of a hand securely holding a black Canon EOS R50 mirrorless camera fitted with an RF-S 18-45mm lens. The user’s index finger is poised over the shutter button, and the thumb rests near the top control dials, set against the green fabric of a jacket.',
  'projects/canon/thumbnail_1x1': 'A front view of an open laptop sitting on a white surface against a soft grey-blue backdrop. The screen displays the Canon Professional Network website, showcasing a technical article titled “Flying high: filming an air display with the EOS C700” with a photo of a pilot inside a cockpit.',
  'projects/cruquius-museum/01_2x1': 'Woman ascending a staircase inside the museum, with typographic quotes from 17th-century poetry and documents displayed on the surrounding walls.',
  'projects/cruquius-museum/02_1x1': 'Two visitors standing in front of a large projected historical illustration of the Cruquius pumping station, part of the museum’s narrative on land reclamation.',
  'projects/cruquius-museum/03_1x1': 'Close-up of a hand interacting with a digital map showing historical topography, part of an interactive display explaining the geography of Haarlemmermeer.',
  'projects/cruquius-museum/04_2x1': 'Museum visitor exploring a display case containing navigation instruments, maps, and archaeological artifacts, with a touch screen integrated into the surface.',
  'projects/cruquius-museum/05_2x1': 'Panoramic view of the gallery featuring an immersive wall projection of historical maps and a portrait of King Willem I, with visitors engaging with the exhibits.',
  'projects/cruquius-museum/06_1x1': 'Woman interacting with a digital touchscreen in front of a large decorative map, using the interface to explore historical information.',
  'projects/cruquius-museum/07_1x1': 'Two visitors interacting with a long display table featuring historical navigation tools, ceramic artifacts, and a digital map interface, in a gallery combining exposed brick and museum lighting.',
  'projects/cruquius-museum/08_2x1': 'Woman examining a large wall-mounted visual timeline that traces the development of steam technology from 1643 onward, featuring historical texts and illustrations.',
  'projects/cruquius-museum/09_2x1': 'Child peering into a reconstructed boiler installation, while two other children in the foreground use audio handsets to explore the exhibit in the “Boiler Room” section.',
  'projects/cruquius-museum/10_1x1': 'Young boy using a touchscreen embedded in a wall panel to learn about the properties and transformations of steam.',
  'projects/cruquius-museum/11_1x1': 'Child interacting with a horizontal touchscreen table, placed in front of a large infographic panel showing engineering data and historical timelines of the pumping station.',
  'projects/cruquius-museum/12_2x1': 'Children interacting with tall, black cylindrical structures that present historical information about steam power, surrounded by other exhibits and timeline graphics.',
  'projects/cruquius-museum/13_2x1': 'Three children closely examining a hands-on model of a steam engine, focusing on its moving mechanical parts.',
  'projects/cruquius-museum/14_1x1': 'A young woman observing a detailed infographic display with historical data, diagrams, and scale models related to the Cruquius pumping station and its steam engines.',
  'projects/cruquius-museum/15_1x1': 'Visitor standing near the massive Cruquius engine installation, surrounded by large iron components and a spiral staircase inside the museum.',
  'projects/cruquius-museum/16_2x1': 'Children seated at a long interactive counter, experimenting with steam engine models, assisted by a woman under a “Stoomlab” sign in the background.',
  'projects/cruquius-museum/cover_3x1': 'Entrance to the Cruquius Museum featuring exposed brick walls and illuminated signage, with a blurred figure walking through the doorway.',
  'projects/cruquius-museum/thumbnail_1x1': 'Museum visitor exploring a display case containing navigation instruments, maps, and archaeological artefacts, with a touch screen integrated into the surface.',
  'projects/family-exhibits/01_2x1': 'Wide view of the archaeological gallery, with large amphora replicas, touchscreen tables, and animated projections illustrating layers of earth and excavation scenes.',
  'projects/family-exhibits/02_1x1': 'Two young girls interacting with a sand-textured touchscreen interface, part of a digital digging game that simulates uncovering buried artifacts in different soil layers.',
  'projects/family-exhibits/03_1x1': 'Close-up of a girl using a circular interactive screen that mimics ancient decorative patterns, part of an archaeology-themed activity about reconstructing cultural objects from fragments.',
  'projects/family-exhibits/04_1x1': 'Two teenagers engaging with a large horizontal touchscreen as part of an interactive archaeological game, set within a gallery where colorful stratigraphic layers are projected on the walls to simulate excavation contexts.',
  'projects/family-exhibits/05_1x1': 'A toddler inserting a puzzle piece into a large interactive ceramic-alike amphora, part of a hands-on archaeological activity, while an adult woman looks on.',
  'projects/family-exhibits/06_2x1': 'Boy and father engaging with an interactive table game where participants place their hands over specific object replicas to trigger animated projections on the wall, revealing excavation layers and archaeological timelines.',
  'projects/family-exhibits/07_1x1': 'Children using a multi-user touchscreen to uncover virtual artifacts in a digging-themed game, while parents look on, in a gallery designed to simulate a layered archaeological dig site.',
  'projects/family-exhibits/08_1x1': 'Young girl smiling while playing with a tactile puzzle on a large amphora replica, part of an interactive installation that invites children to reconstruct broken archaeological artifacts.',
  'projects/family-exhibits/09_2x1': 'A child interacting with replicas of ancient artifacts on a round table; wall projections above respond with animated historical scenes and layers representing excavation contexts. Two adult men are observing the game.',
  'projects/family-exhibits/10_2x1': 'Wide view of a gallery with immersive underwater projections covering the walls; traditional fishing tools, props and interactive screens are arranged on display, and a large stylized pearl shell sits at the center.',
  'projects/family-exhibits/11_1x1': 'Young girl sitting playfully inside a large sculpted pearl shell in the middle of the gallery, surrounded by vivid marine-themed projections.',
  'projects/family-exhibits/12_1x1': 'Three children roleplaying a traditional cooking activity, using tongs to place toy fish over a simulated grill lit with glowing red light to mimic fire.',
  'projects/family-exhibits/13_2x1': 'Child and adult woman exploring an interactive touch display set into a counter, with vibrant coral reef animations projected on the surrounding gallery walls.',
  'projects/family-exhibits/14_1x1': 'Young girl standing in front of a wall display featuring brightly lit circular windows, each showcasing a different sea creature linked to the marine life of the Gulf.',
  'projects/family-exhibits/15_1x1': 'Close-up of a touchscreen game interface with a grid of numbered pearl illustrations, inviting visitors to find the most precious pearl known as the Dana or Jiwan.',
  'projects/family-exhibits/16_1x1': 'Two girls engaging with a digital touchscreen embedded under a large wooden dhow model, exploring pearl-themed interactive content with projected coral reef graphics.',
  'projects/family-exhibits/17_1x1': 'Young boy exploring a large boat model beneath a sail-shaped screen projecting a pearl diving scene, opening side compartments to discover the vessel’s interior features.',
  'projects/family-exhibits/18_2x1': 'Three children using large interactive wooden oars, simulating the rowing experience of pearl divers in a boat installation surrounded by an underwater environment.',
  'projects/family-exhibits/19_1x1': 'Wide view of an immersive energy-themed room with glowing floor tiles and colorful wall graphics depicting Qatar’s energy landscape and infrastructure.',
  'projects/family-exhibits/20_1x1': 'Two children and an adult joyfully interacting with an illuminated game floor, triggering projected animations and feedback related to Qatar’s energy journey.',
  'projects/family-exhibits/21_1x1': 'Child scanning colorful 3D-printed plastic objects shaped like consumer goods using a handheld barcode scanner at an interactive wall.',
  'projects/family-exhibits/22_1x1': 'Group of children standing barefoot on a glowing interactive floor, focusing on triggering visual responses through movement.',
  'projects/family-exhibits/23_2x1': 'Illuminated interactive floor displaying a stylized map of Qatar, with LED-lit illustrations on the wall representing national energy sources. A rainbow-colored screen above the floor provides game instructions in Arabic.',
  'projects/family-exhibits/cover_3x1': 'Exterior view of the National Museum of Qatar, with its iconic interlocking disc design and water features, seen through an artistic sculptural installation in the foreground.',
  'projects/family-exhibits/thumbnail_1x1': 'Children using a multi-user touchscreen to uncover virtual artifacts in a digging-themed game, while parents look on, in a gallery designed to simulate a layered archaeological dig site.',
  'projects/herman-boerhaave/01_2x1': 'A young woman kneeling in front of a glass case containing a bronze bust, carefully observing the sculpture below a graphic wall that combines Herman Boerhaave’s name and stylized portrait.',
  'projects/herman-boerhaave/02_1x1': 'Two visitors standing side by side watching a large screen playing a video interview with English subtitles, in a gallery section centered on experimentation and scientific thought.',
  'projects/herman-boerhaave/03_1x1': 'Glass case displaying a decorative urn placed on a dark pedestal, accompanied by a colorful wall panel that presents contextual information about Boerhaave’s life and work in Leiden.',
  'projects/herman-boerhaave/04_2x1': 'A young woman leaning forward to read a display in a room filled with colorful graphics and scientific illustrations, while a man in the background engages with another exhibit.',
  'projects/herman-boerhaave/05_2x1': 'Two visitors observing a collection of scientific and medical instruments in glass cases, surrounded by vibrant graphic panels illustrating bedside practices and experimental methods.',
  'projects/herman-boerhaave/06_1x1': 'A man in a blue shirt using a tactile interactive station, with buttons and dials, in a gallery filled with historic scientific tools and instructional displays.',
  'projects/herman-boerhaave/07_1x1': 'A young woman carefully examining a historical thermometer encased in glass, set against a brightly colored wall display with interpretive text about Fahrenheit’s innovations.',
  'projects/herman-boerhaave/08_2x1': 'Museum visitor exploring an exhibit of glass-encased scientific instruments and apothecary tools, surrounded by stylized wall graphics referencing laboratory experimentation.',
  'projects/herman-boerhaave/09_2x1': 'Two museum visitors navigating a gallery on bedside teaching, featuring engraved medical scenes, information panels, and historic ceramic vessels inside glass displays.',
  'projects/herman-boerhaave/10_1x1': 'Young woman leaning over a display case to observe a historical scientific object, with detailed background illustrations and text highlighting the tool’s significance.',
  'projects/herman-boerhaave/11_1x1': 'Young man interacting with a botanical display that includes herbarium sheets and plant illustrations, framed by vivid green walls decorated with foliage motifs.',
  'projects/herman-boerhaave/12_2x1': 'Woman closely reading a glass case containing handwritten medical notes, with a backdrop of engraved portraits and a large wall illustration of a teaching scene.',
  'projects/herman-boerhaave/13_2x1': 'Three visitors inside a museum gallery featuring a finely crafted wooden dresser as a central exhibit, with a large family portrait and colorful illustrated walls displaying quotes and silhouettes, including a panel about Carl Linnaeus.',
  'projects/herman-boerhaave/14_1x1': 'Two young visitors conversing in front of a large illustrated wall showing Leiden’s historic botanical garden and university buildings, with nearby panels on botanical research.',
  'projects/herman-boerhaave/15_1x1': 'Close-up of four ornate apothecary jars labeled in Latin, each adorned with a decorative crest, arranged inside a glass display against a clean backdrop.',
  'projects/herman-boerhaave/16_2x1': 'Woman smiling as she observes a glass case displaying fine porcelain tableware, set within a gallery of vivid wall illustrations and a historic portrait hanging in the background.',
  'projects/herman-boerhaave/cover_3x1': 'Entrance area of the exhibition featuring a large wall graphic with the name “Herman Boerhaave” and a silhouette cutout, with a man standing in a dimly lit space beyond the entrance.',
  'projects/herman-boerhaave/thumbnail_1x1': 'Profile view of a man wearing a grey turtleneck sweater, looking at a tall antique wooden scientific instrument displayed inside a glass case. The background features a vibrant blue and orange graphic mural with museum text.',
  'projects/het-steen/01_2x1': 'Female visitor touching a vertical touchscreen display embedded in a large cabinet structure, revealing layered stories through artworks and animated content.',
  'projects/het-steen/02_1x1': 'Distant view of an immersive theatrical installation, with a woman seated in the foreground watching life-sized projections of actors in costume performing inside a recreated artist’s studio.',
  'projects/het-steen/03_1x1': 'Child seated among oversized wooden architectural models, gazing up in awe at a screen embedded in the wooden structure above.',
  'projects/het-steen/04_1x1': 'Woman looking up inside a vertical wooden structure with a digital ceiling screen displaying a kaleidoscopic architectural animation.',
  'projects/het-steen/05_1x1': 'Child interacting with a large touchscreen display embedded in a wooden exhibit structure, surrounded by architectural models and warm lighting.',
  'projects/het-steen/06_2x1': 'Woman exploring a room lined with life-size vertical screens, each presenting cultural stories and visuals from different neighborhoods of Antwerp.',
  'projects/het-steen/07_1x1': 'Woman using a large horizontal touchscreen map alongside a wooden scale model of Antwerp, in a sunlit room with tall windows.',
  'projects/het-steen/08_1x1': 'Woman and child inside an immersive panoramic projection room with floor-to-ceiling visuals of a car terminal and cargo ship.',
  'projects/het-steen/09_2x1': 'Woman and child engaging with a large interactive map table; both smiling and pointing to different elements on the digital surface in a warmly lit room.',
  'projects/het-steen/10_2x1': 'Woman interacting with a horizontal touchscreen exhibit focused on craftsmanship and local industry, featuring large visuals and text in a softly lit space.',
  'projects/het-steen/11_1x1': 'Woman standing in a dimly lit attic space, listening to an audio track through a handset while interacting with a touchscreen display embedded in a wooden podium.',
  'projects/het-steen/12_1x1': 'Two women and a child observing a large vertical digital display showing a high-resolution reproduction of a classical painting, inside a bright gallery space with tall windows.',
  'projects/het-steen/13_2x1': 'A child sits on the floor while a woman stands nearby, both immersed in an interactive installation where colorful visuals and texts about Antwerp’s creative industry are projected onto the floor and wall.',
  'projects/het-steen/cover_3x1': 'Parent and child closely examining the drawers of a historic wooden cabinet in a red-patterned room at Het Steen, discovering tactile and visual elements of Antwerp’s past.',
  'projects/het-steen/thumbnail_1x1': 'Woman and child engaging with a large interactive map table; both smiling and pointing to different elements on the digital surface in a warmly lit room.',
  'projects/interplanetary/01_2x1': 'A two-page infographic titled “Interplanetary” on a starry black background. It maps cosmic distance from Earth and local satellites on the left, past an asteroid belt, to distant star clusters on the right.',
  'projects/interplanetary/02_1x1': 'A close-up of the “Interplanetary” page, showing the bold white title text, an explanatory paragraph, and a data table converting space distances into kilometres, AU, light-years, and parsecs.',
  'projects/interplanetary/03_1x1': 'A close-up of a white page showing a honeycomb grid of space organisations connected above detailed engineering line drawings of the Orion spacecraft and Arkyd telescope.',
  'projects/interplanetary/04_2x1': 'A full two-page spread titled “Agreements” using a white background. It features large interlocking hexagon clusters to map connections between global space agencies, a historical timeline, and a blue investment bar chart.',
  'projects/interplanetary/05_2x1': 'A full two-page infographic titled “International Space Station” on a starry black background. It illustrates a spacecraft’s launch and orbital trajectory over Earth alongside a detailed technical drawing of the ISS.',
  'projects/interplanetary/06_1x1': 'A close-up of the ISS infographic, highlighting data charts that break down the station’s modules between US and Russian segments, astronaut schedules, and orbital stats against a black starry backdrop.',
  'projects/interplanetary/07_1x1': 'A close-up of a white page mapping the Deep Space Network. Blue lines connect Earth ground stations to satellite relays and chart space observatories ordered by their distance in astronomical units.',
  'projects/interplanetary/08_2x1': 'A full two-page spread titled “Communication.” It features a massive, intricate circular diagram of blue lines connecting global tracking antennas to satellites, space telescopes, and deep-space probes.',
  'projects/interplanetary/09_2x1': 'A full two-page infographic titled “The Solar System” on a black background. It features large, textured blue-and-white illustrations of Jupiter, Saturn, and their moons, alongside orbital flight paths of deep space probes.',
  'projects/interplanetary/10_1x1': 'Close-up of a book page featuring a starry black background with bright blue orbital diagrams mapping trajectories between Earth, Venus, and Mars, accompanied by educational text blocks about the interplanetary transport network and the Cassini-Huygens probe.',
  'projects/interplanetary/11_1x1': 'Angled view of an infographic page covered in a dense grid of tiny grey and black little planets labelled with alphanumeric codes. Three large planets callouts break up the grid to display data for the exoplanets Kepler-296d, KOI-3010.01, and Kepler-22b.',
  'projects/interplanetary/12_2x1': 'An open two-page book spread titled “The Milky Way.” The left page shows blue diagrams illustrating the conditions for life alongside a technical drawing of the Kepler Space Telescope. The right page displays a massive data grid of tiny dots cataloging stars and exoplanets.',
  'projects/interplanetary/13_2x1': 'An open two-page book spread titled “The Universe.” The right page features a large graphic of an expanding cone illustrating the timeline of the universe from the Big Bang onwards, paired with an electromagnetic spectrum timeline at the bottom. The left page shows text about cosmic distances and a diagram of the Hubble telescope.',
  'projects/interplanetary/14_1x1': 'Close-up of text and blue diagrams on a white book page detailing methods for measuring cosmic distances, specifically highlighting the scientific concepts of “Parallax” and “Standard candles.”',
  'projects/interplanetary/15_1x1': 'Minimalist view of the corner of a textured black page featuring white text that reads “4.9%” next to a small shaded square. Below it, a caption reads: “Only 4.9% of our Universe is composed of observable matter.”',
  'projects/interplanetary/16_2x1': 'High-angle shot of an open book with a minimalist black two-page spread. The left page features text under a “95.1%” heading explaining dark matter, while the right page is mostly blank, featuring only a small “4.9%” statistic about observable matter in the bottom corner.',
  'projects/interplanetary/17_2x1': 'Close-up of a computer monitor displaying retro, pixelated white text on a black screen. The screen is divided into a “TRANSMITTING:” column showing outbound messages to deep space probes, and a “RECEIVED:” column showing inbound confirmations.',
  'projects/interplanetary/18_1x1': 'A vertical digital graphic on a black background showing instructions titled “@ATLASDSN: HOW TO TWEET TO DEEP SPACE?”. The left side illustrates concentric planetary orbits with lines connecting Earth to six deep-space probes, while the right side lists the Twitter handles and distances for each spacecraft.',
  'projects/interplanetary/19_1x1': 'Black-and-white photo of an art installation. A line-art satellite dish and six spacecraft (Chandra, Kepler, Curiosity, Rosetta, Cassini, Voyager 1) are projected onto a brick wall under the handle @ATLASDSN. In the foreground, a computer monitor displays a live transmission log with usernames, timestamps, and signal power.',
  'projects/interplanetary/20_2x1': 'A clean digital graphic with white line-art on a black background. It shows a large satellite dish emitting signal lines that map directly to six labelled spacecraft: Chandra, Kepler, Curiosity, Rosetta, Cassini, and Voyager 1.',
  'projects/interplanetary/21_2x1': 'Two tablets side-by-side displaying Twitter posts on a dark background. The left screen shows a tweet by Marco Ferrari explaining how to interact with the art installation, while the right screen shows a tweet by Ivor Williams about live tweeting to Voyager 1, both accompanied by photos of the installation.',
  'projects/interplanetary/22_1x1': 'Digital graphic showing retro, white pixelated text on a black background under the header “TRANSMITTING:”. It logs outbound transmissions from users to deep space missions, including Curiosity, Rosetta, Cassini, Voyager 1, and Kepler, listing exact timestamps and signal power in kilowatts.',
  'projects/interplanetary/23_1x1': 'Digital graphic showing retro, white pixelated text on a black background under the header “RECEIVED:”. It displays logs of incoming tweets containing short messages, target spacecraft handles, timestamps, and kilowatts received.',
  'projects/interplanetary/24_2x1': 'Black-and-white photograph of an art installation room. An interactive display mapping a satellite dish to deep space probes is projected on a brick wall. In the foreground, a computer monitor shows data logs next to a seated person using their smartphone.',
  'projects/interplanetary/cover_3x1': 'A panel composed of 2 images. On the left: a minimalist white book cover titled “Atlas of Contemporary Networks,” listing scientific topics vertically. On the right, a retro terminal screen displaying a data log of power commands transmitted to the Curiosity, Rosetta, and Cassini spacecraft.',
  'projects/interplanetary/thumbnail_1x1': 'Angled shot of a book cover with an off-white background. Black text lists words like “Human,” “Machine,” “Flora,” “Fauna,” and “Interplanetary” in a descending stepped pattern, ending with the bold title “Contemporary Networks.”',
  'projects/joh-enschede/01_1x1': 'Display on bookmaking, featuring a historical printing press surrounded by books and miniature figures, with suspended printed pages above and colorful stained glass at the back.',
  'projects/joh-enschede/02_1x1': 'Typography-themed station with metal type installations hanging overhead, display cases with printing materials below, and stained glass windows adding depth to the gallery.',
  'projects/joh-enschede/03_1x1': 'Banknote station with large printing rollers suspended above a display case of financial documents, set against an exposed brick wall and vibrant stained glass inspired by currency design.',
  'projects/joh-enschede/04_1x1': 'Interactive station with antique tools and a touchscreen, set against a stained glass window featuring collage-style banknote imagery and historical references.',
  'projects/joh-enschede/05_1x1': 'Close-up of a vibrant stained glass window featuring a collage of portraiture, patterns, and typographic elements from Dutch banknotes and various printed motifs and patterns.',
  'projects/joh-enschede/06_1x1': 'Display case containing metal printing tools and lead type molds, beneath a mounted infographic panel explaining the process of making lead type.',
  'projects/joh-enschede/07_1x1': 'Two children wearing headphones and holding clipboards, engaging with an interactive exhibit on printing techniques and history.',
  'projects/joh-enschede/08_1x1': 'Woman engaging with a hands-on printing exhibit, pulling a lever on a wooden structure below a screen that explains how to set up and use a historical press.',
  'projects/joh-enschede/09_1x1': 'Two young women reading and discussing a book displayed on a glass-topped museum table, surrounded by other printing-related displays and exhibition graphics.',
  'projects/joh-enschede/10_1x1': 'Two boys interacting with an illuminated display table, one pointing to a printing-related exhibit beneath the glass, with educational diagrams about lead type in the background.',
  'projects/joh-enschede/11_2x1': 'Man and woman smiling as they engage with a digital screen embedded in a display table, surrounded by colorful exhibition elements and brick walls.',
  'projects/joh-enschede/12_1x1': 'Close-up of two visitors interacting with a touchscreen showing historical Dutch banknote specimens, pointing to enlarged images on the screen.',
  'projects/joh-enschede/13_1x1': 'Detailed view of a digital display featuring an interactive design tool, where a user is selecting security features for a banknote as part of an educational museum experience.',
  'projects/joh-enschede/14_1x1': 'Two young girls interacting with a touchscreen display in the museum, one pointing at the interface while the other attentively observes, with printing equipment visible in the background.',
  'projects/joh-enschede/15_1x1': 'Group of children gathered around a display case labeled “De Duitse stempelsnijder” (“The German Punchcutter”), observing and discussing its contents, with an adult guiding them.',
  'projects/joh-enschede/16_2x1': 'Close-up of two adults smiling and using an interactive digital screen labeled “Wealth in letters,” with a printing press and suspended sheets visible above.',
  'projects/joh-enschede/cover_3x1': 'Young man closely inspecting a backlit historical timeline of portraits and key events in the legacy of Joh. Enschedé, a Dutch printer of value documents.',
  'projects/joh-enschede/thumbnail_1x1': 'Group of children gathered around a display case labeled “De Duitse stempelsnijder” (“The German Punchcutter”), observing and discussing its contents, with an adult guiding them.',
  'projects/living-planet/01_2x1': 'Family of four gathered around a touchscreen in the natural history gallery, as the mother points toward a taxidermy animal in the exhibit, surrounded by a diverse array of mounted species.',
  'projects/living-planet/02_1x1': 'Taxidermy dingo displayed on a white platform, surrounded by bears and wild cat specimens in an open exhibition space.',
  'projects/living-planet/03_1x1': 'Young woman pointing toward a group of taxidermy animals while standing next to an interactive screen displaying species-related content.',
  'projects/living-planet/04_1x1': 'Young boy in a red t-shirt looking up in awe, surrounded by taxidermy animals in a white exhibition space.',
  'projects/living-planet/05_1x1': 'Woman wearing a face mask pointing toward an animal specimen while two young children lean over a low railing in a gallery filled with large taxidermy mammals.',
  'projects/living-planet/06_2x1': 'A cheetah and an African wild dog stand side by side on a display platform, surrounded by various birds and mammals.',
  'projects/living-planet/07_1x1': 'Teenage visitor wearing a mask and green checkered shirt, engaging with an angled touchscreen among mounted animal specimens.',
  'projects/living-planet/08_1x1': 'Close-up of a touchscreen interface titled “Vivre sur la Terre” (“Living on Earth”) with a visual network of animal images and taxidermy specimens in the background.',
  'projects/living-planet/09_2x1': 'Mother and young child standing in front of a deer specimen while the child gestures excitedly, with other visitors and animal displays in the background.',
  'projects/living-planet/10_2x1': 'Two young children exploring a yellow circular hands-on table with small animal models, including one placed on top, tactile elements, and circular openings.',
  'projects/living-planet/11_1x1': 'A woman seated at a circular yellow interactive station using a touchscreen surrounded by animal figures, with mounted taxidermy animals in the background.',
  'projects/living-planet/12_1x1': 'Child interacting with a touchscreen embedded in a curved table showing a game about identifying camouflaged animals, with taxidermy specimens displayed nearby.',
  'projects/living-planet/13_2x1': 'Adult and child interacting with a yellow circular hands-on table featuring small colored blocks inside a transparent dome, within a gallery of taxidermy animals.',
  'projects/living-planet/14_1x1': 'Two children examining yellow hands-on tables with circular openings and small animal models placed inside.',
  'projects/living-planet/15_1x1': 'Visitors gather around a large immersive projection showing abstract, colourful nature imagery and a white branching structure in the center.',
  'projects/living-planet/16_1x1': 'Wide view of a museum gallery with circular display platforms presenting taxidermy animals, interactive screens, and low yellow tables integrated among the specimens.',
  'projects/living-planet/17_1x1': 'Close-up of a touchscreen showing a Dutch-language interactive explaining how oceans produce oxygen, with visuals of phytoplankton and coral reefs.',
  'projects/living-planet/18_2x1': 'Curved wall projection displaying four large interactive touchscreens, each in front of a section of animated visuals representing different ecosystems, such as grasslands, forests, and ocean life.',
  'projects/living-planet/19_1x1': 'A woman stands in a dimly lit gallery space, interacting with a touchscreen in front of a natural history exhibit featuring an elk and a scenic tundra backdrop, with wolves and other animals displayed behind her and in the background.',
  'projects/living-planet/20_1x1': 'Close-up of a horizontal touchscreen showing an interface with a rainforest image, a location map, biodiversity stats, and a finger selecting one of the circular data points.',
  'projects/living-planet/21_1x1': 'A woman engaging with a large digital table displaying an interactive globe, surrounded by nature-themed projections of underwater vegetation and marine life.',
  'projects/living-planet/22_1x1': 'A woman standing in an immersive room with walls covered in large-scale projections of forest and mountain environments, surrounded by vivid color and light.',
  'projects/living-planet/23_2x1': 'Immersive installation showing high-resolution projections of a chipmunk on one wall and a grazing reindeer on the other, wrapping around freestanding structures in the space.',
  'projects/living-planet/cover': 'Wide-angle view of a gallery filled with taxidermy animals arranged along curved white arches, showcasing biodiversity across species and environments.',
  'projects/living-planet/thumbnail_1x1': 'Mother and young child standing in front of a deer specimen while the child gestures excitedly, with other visitors and animal displays in the background.',
  'projects/maker-park/01_2x1': 'Daytime view of Ilmi Center showing families and school children walking toward the iconic reflective sphere, surrounded by gardens and flowering trees.',
  'projects/maker-park/02_1x1': 'Portrait of a young boy smiling in traditional Saudi attire, representing the target audience of the educational initiative.',
  'projects/maker-park/03_1x1': 'Aerial night rendering of the Ilmi Center lit up against a dark desert landscape, with illuminated pathways and the luminous central sphere at the heart of the design.',
  'projects/maker-park/04_2x1': 'Front-facing rendering of Ilmi Center at dusk, showing visitors entering the museum through a tunnel-like entrance beneath the glowing orb.',
  'projects/maker-park/05_2x1': 'Colorful 3D illustration of a robot hands holding a smartphone displaying the “Maker Park” gate from the Ilmi app, with gamified learning visuals in the background.',
  'projects/maker-park/06_1x1': 'Cartoon robot wearing a green jersey with the number 1, cheerfully raising a golden trophy with confetti falling around, celebrating a game achievement on a bright blue background.',
  'projects/maker-park/07_1x1': 'A close-up, high-angle shot of a person holding a smartphone in their hands. The phone screen displays a vibrant, cartoonish game menu featuring a blue gated entrance, a green robot character, and Arabic text that reads “Maker Park.”',
  'projects/maker-park/08_2x1': 'A cheerful robot holds its face in surprise next to a floating game controller and a smartphone showing a colorful hexagonal map interface from the educational platform, all set against a vibrant gradient background.',
  'projects/maker-park/cover_3x1': 'Architectural rendering of Ilmi Center at sunset, featuring a glowing spherical structure at the center of a landscaped cultural park filled with visitors.',
  'projects/maker-park/thumbnail_1x1': 'A close-up, high-angle shot of a person holding a smartphone in their hands. The phone screen displays a vibrant, cartoonish game menu featuring a blue gated entrance, a green robot character, and Arabic text that reads “Maker Park.”',
  'projects/middelen-meter/01_2x1': 'Three smartphone screens showing the app onboarding flow: the initial loading screen, a welcome message with a “START” button, and a tutorial screen explaining how to use the circular time dial to select a usage moment.',
  'projects/middelen-meter/02_1x1': 'The substance selection screen (Step 1 of 4) in Dutch, asking “Wat wil je bijhouden?”. It features four large, color-coded buttons with text and icons for tracking: Alcohol (pink), Sigaretten (orange), Joints (green), and Slaappillen (blue).',
  'projects/middelen-meter/03_1x1': 'The time selection screen (Step 2 of 4) for alcohol tracking, asking “Wanneer dronk je?”. A large, interactive central circular dial is set to “dinsdag 25 okt. middag” with a sun icon, above a white “VERDER” button.',
  'projects/middelen-meter/04_2x1': 'Three variations of the time selection screen (Step 2 of 4) customised for different substances, showing specific questions and color-coded dials for tracking smoking cigarettes, smoking joints, or taking sleeping pills.',
  'projects/middelen-meter/05_2x1': 'Three screens showing the alcohol consumption setup: a grid overlay to select specific drinks (like bier, wijn, sterk), Step 3 of 4 to log the specific amount (1 “bier light” of 25 cl), and Step 4 of 4 to select a tracking duration from 1 to 4 weeks.',
  'projects/middelen-meter/06_1x1': 'A setup completion pop-up window reading “GOED GEDAAN!” with a checklist confirming the substance is chosen, the last usage is set, and the tracking plan is made, above a prominent pink “START” button.',
  'projects/middelen-meter/07_1x1': 'The main app dashboard on day 1 of 7, displaying the text “Vandaag” above a central pink plus icon and a large blue button that reads “NIETS GEDRONKEN DE HELE DAG” to quickly log a sober day.',
  'projects/middelen-meter/08_2x1': 'Three variations of the daily dashboard interface: the left shows logged alcohol entries (1 light beer and 4 glasses of wine), the centre shows the “sober today” button for alcohol, and the right shows a cigarette tracking screen confirming “Vandaag niets gerookt” with a smiley face.',
  'projects/middelen-meter/09_2x1': 'Three app pop-up screens: a reminder to accurately log all parts of the previous day, a pink congratulations screen with a smiley face for not drinking today, and a “HERINNER MIJ” window to set an alarm reminder for logging usage.',
  'projects/middelen-meter/10_1x1': 'The main app dashboard on day 3 of 7, displaying a progress bar, a central time-of-day selection dial, a pink plus button for custom logging, and a primary button that reads “NIETS GEDRONKEN DE HELE DAG”.',
  'projects/middelen-meter/11_1x1': 'An app screen titled “GEBRUIK PER DAG” showing a pink-themed weekly bar chart broken down by day parts (ochtend, middag, avond, nacht). A smiley face highlights a day with zero consumption, and a button link at the bottom reads “Aantal standaard glazen”.',
  'projects/middelen-meter/12_2x1': 'Three side-by-side variations of the “GEBRUIK PER DAG” weekly bar chart screen. Each showcases a different substance tracking color scheme: orange for cigarettes, green for joints, and blue for sleeping pills, with consumption broken down by morning, afternoon, evening, and night.',
  'projects/middelen-meter/13_2x1': 'Three side-by-side smartphone mockups displaying the “OVERZICHT” screen. The screens show various timeline views of alcohol and multi-substance tracking data across 1 week, 2 weeks, and 4 weeks using colored vertical bar charts.',
  'projects/middelen-meter/14_1x1': 'A hand holding a smartphone displaying the “OVERZICHT” dashboard screen. The interface shows a weekly bar chart comparing alcohol (pink bars) and cigarette (orange bars) usage data from October 24 to October 30.',
  'projects/middelen-meter/15_1x1': 'An informational screen within the app detailing alcohol measurements, titled “Standaardglas alcohol: 10g = 12.7ml pure alcohol”. Below the title is an illustrative grid displaying standard units and measurements for different drink types, including beer, wine, aperitifs, and spirits.',
  'projects/middelen-meter/16_2x1': 'Three smartphone mockups side-by-side displaying concluding app modals: a congratulations window asking to start a new tracking cycle, a help window with a button link reading “OP ZOEK NAAR HULP?”, and a reset confirmation screen warning that all data will be deleted.',
  'projects/middelen-meter/cover_3x1': 'Close-up of a smartphone screen displaying the dark blue splash screen of the “Middelen Meter” app, featuring a geometric mountain logo in pink, yellow, and blue with a loading spinner.',
  'projects/middelen-meter/thumbnail_1x1': 'The main app dashboard on day 1 of 7, displaying the text “Vandaag” above a central pink plus icon and a large blue button that reads “NIETS GEDRONKEN DE HELE DAG” to quickly log a sober day.',
  'projects/parassita/01_1x1': 'Three copies of “Parasita” magazine arranged together on a surface. Each issue features a unique black and white cover illustration, a human heart with pink text, a young girl’s portrait with yellow text, and a planetary space scene with teal text.',
  'projects/parassita/02_1x1': 'A close-up view of a magazine cover featuring a black and white line-art portrait of a young girl with wavy hair. The yellow title “parasita” is visible at the top right, and a black box with yellow text sits at the bottom.',
  'projects/parassita/03_1x1': 'An internal page of a magazine featuring a grayscale architectural drawing of clotheslines hanging outside a building structure. A bright yellow circular graphic symbol is overlaid near the bottom of the page.',
  'projects/parassita/04_1x1': 'A close-up shot looking down into the complex zine-style folding structure of an open magazine. The unique layout reveals glimpses of inner pages with text, illustrations, and a distinct concertina fold.',
  'projects/parassita/05_2x1': 'An open spread of a magazine laid flat on a table. The right page features bold, black typography stating “A magazine for Italians who live in Amsterdam & Dutch who love Italy,” alongside columns of article text and a diagram.',
  'projects/parassita/06_2x1': 'Several opened and closed issues of “Parasita” magazine scattered on a surface. Visible pages show an “Index set” roadmap diagram, a planetary space cover labeled “Water Part 3/3”, and the human heart illustration issue.',
  'projects/parassita/07_1x1': 'A fully unfolded, multi-panel editorial layout showcasing infographics. It features linear “Index set” and “This issue” timelines with numbered circular icons, graphic diagrams of a folding box, and small black and white photographs.',
  'projects/parassita/08_1x1': 'An infographic magazine spread printed in black, white, and a bright yellow block background. It reads “The only film couple who never quarrelled” and depicts a horizontal timeline of film titles, accompanied by comic-style portraits and a movie still.',
  'projects/parassita/09_1x1': 'A close-up, angled view of the cover of “Parasita” magazine, subtitled “Family”. It features a detailed black and white cross-section illustration of a human heart, with the title text printed in vibrant pink.',
  'projects/parassita/10_1x1': 'Cover of Parassita magazine, Part 3/3, titled “Water,” featuring a detailed black-and-white ink illustration of Saturn, a planetary surface, and a complex space probe.',
  'projects/parassita/11_2x1': 'Open magazine spread showing an article titled “Valeria and her moving Italian family” and an overlapping page titled “Guten Morgen Riccardo!” featuring a portrait of a bearded man holding an iPod.',
  'projects/parassita/12_1x1': 'Upside-down infographic layout comparing Venetian “Sarde in saor” and Dutch herring dishes, featuring description paragraphs, a regional map of Italy, and an illustration of a fish salad.',
  'projects/parassita/13_1x1': 'Infographic page detailing an interview and a vertical travel timeline from 1972 to today, tracking a family’s moves across global cities using interlocking colored circles.',
  'projects/parassita/14_2x1': 'Two overlapping infographic sheets; one is titled “Belli di mamma: The Italian youth” with a graphic of a person walking through a door, and the other is titled “Sea drilling: The Next Referendum.”',
  'projects/parassita/15_1x1': 'Infographic detail comparing data on young Italians living with parents (“Mama’s boys”, totalling over 9 million) versus those moving abroad (“Expat boys”, totalling over 54,000), with lists of reasons for each.',
  'projects/parassita/16_1x1': 'Detailed infographic map of Southern Italy and the Adriatic Sea, showing offshore hydrocarbon extraction zones marked with gridded patterns and data visualisation dots.',
  'projects/parassita/17_1x1': 'Infographic page with sections on Italian household types, global happiness rankings showing Italy at 50th, and 2014 - 2015 birth/death rates alongside illustrations of pasta and a mock bicycle rental receipt.',
  'projects/parassita/18_1x1': 'Infographic page featuring a large technical line drawing of a cruise ship, a map of the Venetian lagoon marking floodgate locations, and a diagram explaining how the Mose barrier works.',
  'projects/parassita/19_2x1': 'Infographic poster titled “The Mafia Famiglia” featuring a map of Italy color-coded by crime organisation territories and a black-and-white comic illustration depicting a mafia hierarchy chart.',
  'projects/parassita/20_2x1': 'An open infographic page titled “The Blue Italy” that maps out national weather phenomena. The page features a minimalist outline of Italy overlaid with red rain droplets, gray snow asterisks, and teal flood zones, accompanied by a detailed data legend on the right.',
  'projects/parassita/21_1x1': 'A close-up, angled shot of a printed timeline infographic. A thick black diagonal line acts as the main axis, marked with specific years, small circular country codes, and varying sizes of red circles that highlight social and political milestones with text blocks.',
  'projects/parassita/22_1x1': 'An angled look into the folds of an open infographic poster. The center features a prominent black-and-white ink illustration of two laughing women, surrounded by text columns detailing global facts and legal milestones.',
  'projects/parassita/23_2x1': 'A wide view of a large, geometric folded infographic spread. The left side features a bold coral-red circular graphic with text reading “...what do Italians think about this topic?”, while the right side displays a historical timeline and a black-and-white illustration.',
  'projects/parassita/24_2x1': 'A folded infographic spread mapping migration routes across the Mediterranean Sea to Italy, titled “Sea: a pass to Europe.” The layout combines a pale teal geographic map, a sequence of black proportional data circles, and fine lines showing transit paths from North Africa.',
  'projects/parassita/25_1x1': 'A detailed view of a migration map infographic showing the Mediterranean Sea. Teal circular hubs mark North African cities like Tripoli and Benghazi, with a dense web of connecting lines radiating northward toward Italian coastal arrival points.',
  'projects/parassita/26_1x1': 'An infographic panel titled “Europe, a pass to hope” regarding the 2015 migrant crisis. It features a green line drawing of one person helping another, a concentric green demographic ring chart, and a descriptive text column labeled “Who?”.',
  'projects/parassita/27_2x1': 'Three folded booklets stacked diagonally, each with a “parasita” logo in different colors (yellow, pink, teal) where the “s” and “i” form a wave, accompanied by black-and-white illustrations.',
  'projects/parassita/28_2x1': 'A graphic design diagram illustrating how to fold paper into a multi-page booklet. “Sheet 1” shows a flat page with dashed fold lines, while “Sheet 2” and “Sheet 3” show the final folded accordion structures. A three-color palette circle icon sits beneath each diagram.',
  'projects/parassita/29_1x1': 'A minimalist black logo of the word “parasita” on a white background. The logo uses a clean, lowercase sans-serif typeface, with the letters “s” and “i” uniquely replaced by a continuous, looping vertical S-curve line.',
  'projects/parassita/30_1x1': 'A minimalist graphic icon featuring a black circular border on a white background. Inside the circle is an abstract, continuous line that twists into a vertical S-curve or fluid ribbon motif, representing the standalone brand mark derived from the “parasita” logo.',
  'projects/parassita/31_2x1': 'A graphic design diagram detailing a four-step assembly process for a folded booklet. “Step 1” through “Step 4” visually demonstrate how three separate components nest and fold together into a single, compact booklet.',
  'projects/parassita/cover_3x1': 'A cropped shot of three copies of “Parasita” magazine, stacked slightly overlapping. The title text is identical on all three, but colored differently in yellow, pink, and teal, over different black and white cover drawings.',
  'projects/parassita/thumbnail_1x1': 'Three copies of “Parasita” magazine arranged together on a surface. Each issue features a unique black and white cover illustration, a human heart with pink text, a young girl’s portrait with yellow text, and a planetary space scene with teal text.',
  'projects/prodemos/01_2x1': 'A girl smiles while another student films her using a tablet, capturing a scene for the interactive assignment indoors.',
  'projects/prodemos/02_1x1': 'Three girls stand in a tree-lined area, focused on a tablet screen as they work together on one of the GPS-based challenges.',
  'projects/prodemos/03_1x1': 'Three girls sit on a park bench, looking at a tablet together, one pointing at the screen as they discuss.',
  'projects/prodemos/04_1x1': 'Tablet screen showing a final congratulatory screen in Dutch with stars and a crown, marking the completion of the game.',
  'projects/prodemos/05_1x1': 'Tablet screen displaying the structure of the activity and tasks to complete, with headings and icons in purple on an orange background.',
  'projects/prodemos/06_2x1': 'A group of teenage students gathers in a leafy urban area, wearing red lanyards and name badges. Some are seated on a bench while others stand around them, smiling and holding tablets as part of an educational activity.',
  'projects/prodemos/07_1x1': 'Two girls stand on the sidewalk in front of a staircase, one holding a tablet and the other gesturing while talking, engaged in discussion.',
  'projects/prodemos/08_1x1': 'Four young men stand under a tree, gathered around a tablet, collaborating on a task during the outdoor activity.',
  'projects/prodemos/09_2x1': 'Close-up of a tablet screen showing a digital interface where users select a Dutch government minister as part of the game.',
  'projects/prodemos/cover_3x1': 'Five teenage girls walk side by side through a city street, smiling and chatting. They wear red lanyards with badges, and some hold tablets as part of an educational activity.',
  'projects/prodemos/thumbnail_1x1': 'Group of teenagers sitting and standing around a park bench, holding tablets and wearing event badges during an outdoor learning activity.',
  'projects/shifting-image/cover_3x1': 'Bust of Johan Maurits positioned in front of a wall covered with identical sculpted heads. Around the room, visitors observe large colonial paintings and immersive wall projections of tropical landscapes and ruins.',
  'projects/shifting-image/thumbnail_1x1': 'Close-up of a woman gazing at a large colonial painting depicting a noblewoman with children. The woman stands in a dark gallery lit by focused spotlights on the artworks.',
  'projects/shifting-images/01_2x1': 'Exhibition room with colonial portraits and a timeline wall. A large painting of a woman accompanied by a white child and a Black child dominates the foreground, while visitors quietly observe other paintings in the surroundings.',
  'projects/shifting-images/02_1x1': 'A woman interacts with a touchscreen display in front of a large, ornately framed portrait of Johan Maurits. In the background, projected images and a smaller portraits of two Black men are visible.',
  'projects/shifting-images/03_1x1': 'Close-up of a woman gazing at a large colonial painting depicting a noblewoman with children. The woman stands in a dark gallery lit by focused spotlights on the artworks.',
  'projects/shifting-images/04_2x1': 'Two women explore a gallery space featuring a detailed white architectural model and framed portraits of Black men. On the left wall, an exhibition timeline in Dutch and English provides historical context.',
  'projects/shifting-images/05_2x1': 'Gallery scene with a bust of Johan Maurits in the center, surrounded by wall-mounted colonial paintings and immersive projections of exotic landscapes. Several visitors explore the room independently.',
  'projects/shifting-images/06_1x1': 'White architectural model of a classical building, made of imitation sugar cubes and displayed under a spotlight. The model sits on a circular base covered in loose sugar cubes, all set within a dark exhibition room.',
  'projects/shifting-images/07_1x1': 'A woman stands closely in front of a large colonial portrait of a white woman accompanied by a Black servant. Projected market scenes and paintings are layered across the back wall.',
  'projects/shifting-images/08_2x1': 'Side view of a woman reading from a touchscreen next to a large white architectural model of a neoclassical building, made of imitation sugar cubes. The installation is surrounded by a base of loose sugar cubes and illuminated in a dark room.',
  'projects/shifting-images/09_2x1': 'Panoramic view of the exhibition room with a timeline wall, large projected colonial portraits, and a seated visitor. The bust of Johan Maurits appears in the foreground, partially turned.',
  'projects/shifting-images/10_1x1': 'Bust of Johan Maurits in a spotlight, set against a textured wall covered in repeating versions of the same sculpted face. The statue’s elaborate military uniform and expression are clearly visible.',
  'projects/shifting-images/11_1x1': 'A young woman stands in front of a series of framed landscape paintings, attentively engaging with a touchscreen. Projected scenes of natural environments extend across the walls in the background.',
  'projects/shifting-images/12_2x1': 'Interactive panel titled “Wat vraagt u zich af?” (“What would you like to know?”) invites visitors to reflect on the legacy of Johan Maurits and colonial history, featuring a mix of Dutch and English explanatory text and survey questions.',
  'projects/vanishing/01_2x1': 'Screenshot of the 3D interactive extinction data visualisation on a laptop, showing 14,448 endangered species plotted as coloured geometric shapes in a dark virtual space, with species names and a legend visible`',
  'projects/vanishing/02_1x1': 'Close-up of a hand using Leap Motion gesture control above a laptop keyboard, navigating the 3D extinction visualisation on screen, with species names and coloured shapes visible`',
  'projects/vanishing/03_1x1': 'A person’s hand resting on top of a Leap Motion device near a MacBook trackpad while the screen shows the colourful extinction data visualisation with geometric shapes representing animal species.',
  'projects/vanishing/04_2x1': 'Laptop displaying the companion app’s onboarding screen for the 3D extinction visualisation, with illustrated hand gesture diagrams explaining Z-axis and X/Y-axis navigation controls, and a caption reading “Moving your hand, you can control the camera inside the visualisation”.',
  'projects/vanishing/05_2x1': 'Three Android smartphone screens showing the Deep into the Animal Extinction companion app: the first displays a navigation instruction with a hand gesture diagram, the second shows the species legend (Mammals, Birds, Amphibes, Fish), and the third shows a species detail page for the Amur Leopard marked as critically endangered.',
  'projects/vanishing/06_1x1': 'Laptop showing the companion app species detail page for the Wyoming Toad (Anaxyrus baxteri), with a white skeletal illustration, an “Extinct in the wild” status bar in red, a US map highlighting Wyoming, and species data including taxonomy, threats, and description.',
  'projects/vanishing/07_1x1': 'Laptop showing the companion app species detail page for a great white shark, with a white anatomical illustration on a dark background, a threat-level colour bar, and a world map indicating its range.',
  'projects/vanishing/08_2x1': 'Laptop displaying the companion app detail page for the Amur Leopard (Panthera Pardus Orientalis), showing a white skeletal illustration, critically endangered status bar, geographic range map, and taxonomic data on a dark background.',
  'projects/vanishing/09_2x1': 'Black screen with a thin white border and the white text “Not everything that vanishes does it silently” centred in the lower third, serving as a title card or intro screen for the sound sonification piece',
  'projects/vanishing/10_1x1': 'Video thumbnail showing the extinction data visualisation paused at the year 1996, with coloured geometric shapes representing Mammals, Birds, Amphibes, Fishes, and Reptiles scattered across a black screen, with a play button overlay.',
  'projects/vanishing/11_1x1': 'Still from the sound sonification piece showing the year 2013, with coloured geometric shapes spread across five animal class columns (Mammals, Birds, Amphibes, Fishes, Reptiles) on a black background.',
  'projects/vanishing/12_2x1': 'Black screen with white text reading: “Every ten seconds of what you will be hearing corresponds to the animal species entered in the Red List during that year. The years are those in which the Red List was updated.”',
  'projects/vanishing/13_2x1': 'Double-page spread from the Vanishing printed atlas showing the Camouflage chapter, with illustrated military vehicles, aircraft, tanks, and soldiers on the left and a full-bleed illustration of soldiers in combat camouflage on the right, printed in black and red on white.',
  'projects/vanishing/14_1x1': 'Close-up photograph of the printed atlas pages showing detailed black and red Risograph illustrations of military vehicles and equipment from the Camouflage chapter, with text annotations visible.',
  'projects/vanishing/15_1x1': 'Close-up of the printed Physical Identity atlas spread, showing a detailed black ink illustration of the Stalking Cat with tiger-like facial tattoos, with caption text and diagrams visible below.',
  'projects/vanishing/16_2x1': 'Double-page spread from the Physical Identity chapter of the Vanishing atlas, with large illustrated portraits of body-modified individuals, data panels on modification types, cosmetic surgery statistics, and gender reassignment steps, in black and red on white.',
  'projects/vanishing/17_2x1': 'Double-page spread from the Vanishing atlas showing the Anonymity chapter, with an illustration of a man looking at his phone on the left and an isometric maze-like labyrinth diagram of data networks on the right, in black and red on white.',
  'projects/vanishing/18_1x1': 'Close-up of printed Anonymity and Camouflage atlas spreads layered together, showing isometric labyrinth and network diagrams in red and black, a red wireframe face illustration, and a large illustrated figure in the foreground.',
  'projects/vanishing/19_1x1': 'Close-up of the printed Languages atlas spread, showing a dense red full-bleed text page overlapping white pages with isometric diagrams, endangered language maps, and data panels on causes of language loss and revitalisation.',
  'projects/vanishing/20_2x1': 'Double-page spread from the Languages chapter of the Vanishing atlas, with isometric diagrams illustrating causes of language endangerment, a map of endangered languages by nation, effect and solution icons, and a dense red dictionary-style text column.',
  'projects/vanishing/21_2x1': 'Double-page spread from the Extinction chapter of the Vanishing atlas, dominated by a large red-and-black illustration of an Amur Leopard with its skeleton visible, alongside an identikit data panel, cause-of-extinction icons, case studies of extinct species, and a mammoth cloning diagram.',
  'projects/vanishing/22_1x1': 'Close-up of the printed Extinction atlas spread, showing red-spotted leopard fur and skeletal illustration detail, with a small world map, Amur Leopard identikit portrait, and data labels for places, habitats, threats, and weight.',
  'projects/vanishing/23_1x1': 'Close-up photograph of the printed Universe atlas spread, showing a polar projection Earth map with red location markers on a black starfield background, with orbital lines, a Dead Sea diagram, and a whale illustration in the lower portion.',
  'projects/vanishing/24_2x1': 'Double-page spread from the Universe chapter of the Vanishing atlas, with a polar projection Earth map on a black starfield, text panels on cosmological phenomena, and landscape illustrations of endangered places including Venice, the Amazon, and the Maldives.',
  'projects/vanishing/cover_3x1': 'Two-panel image: the Vanishing atlas black hardcover with its chapter index in white diagonal text, alongside a hand over a MacBook keyboard displaying the colourful 3D animal extinction data visualisation.',
  'projects/vanishing/thumbnail_1x1': 'A person’s hand resting on top of a Leap Motion device near a MacBook trackpad while the screen shows the colourful extinction data visualisation with geometric shapes representing animal species.',
}

const sections = {
  home: {
    slug: 'home',
    href: '/',
    menu_title: 'Anna Nogaré',
    menu_aria_label: 'Back to homepage',
    title: 'Anna Nogaré; Interpretive Design Director & Accessibility Strategist, CPACC',
    description: 'Creating meaningful experiences that everyone can enjoy.',
    subtitle: 'I lead and design digital, physical, and hybrid experiences that turn complex content into inclusive journeys across cultural, educational, tourism, and public environments.',
    cta_quote: 'It’s not about <em>them</em> in the end. It’s about <em>all of us</em> from the very start.',
  },

  about: {
    slug: 'about',
    href: '/about/',
    menu_title: 'About',
    menu_aria_label: 'Learn more about me',
    title: 'About me',
    description: 'I’m Anna Nogaré, an Interpretive Design Director & Accessibility Strategist working across cultural, educational, tourism, and public environments. A multidisciplinary designer at heart, I combine strategic leadership with hands-on design across digital, physical, and hybrid experiences, translating complex content into meaningful and inclusive journeys for diverse audiences.',
    cta_quote: 'Great ideas start with simple conversations.',
  },

  contact: {
    slug: 'contact',
    href: '/contact/',
    menu_title: 'Contact',
    menu_aria_label: 'Get in touch with me',
    title: 'Contact',
    description: 'If you’d like to discuss a project, ask a question, or simply say hi, I’d love to hear from you.',
    cta_quote: 'Always up for big ideas, or just a good decaf Americano.',
  },

  manifesto: {
    slug: 'manifesto',
    href: '/manifesto/',
    menu_title: 'Manifesto',
    menu_aria_label: 'Read my Accessibility Manifesto',
    title: 'Accessibility Manifesto',
    description: 'It’s not about them in the end of a project. It’s about all of us from the very start.',
    cta_quote: 'Accessibility is <br/>strategic design. <br/>Not a compromise.',
  },

  projects: {
    slug: 'projects',
    href: '/projects/',
    menu_title: 'Selected <br />projects',
    menu_aria_label: 'Explore selected projects',
    title: 'Selected projects',
    description: 'A selection of projects that explore different ways of creating meaningful experiences for diverse audiences. Each one reflects a unique goal, always shaped by a people-first approach.',
    cta_quote: 'Let curiosity shape your story. Together, we make it real.',
  },

  resources: {
    slug: 'resources',
    href: '/resources/',
    menu_title: 'Resources',
    menu_aria_label: 'Read my opinions',
    title: 'Resources',
    description: 'A collection of articles, opinions, thoughts, and reflections.',
    subtitle: 'A collection of articles, opinions, thoughts, and reflections gathered over time, mostly around accessibility as strategic design. Some are polished, some are raw, some somewhere in between. All are still evolving.',
    subtitle_2: 'This is a space to think and share out loud, because the more we talk about these things, the harder they are to ignore.',
    cta_quote: 'The more we talk about it, the harder it gets to ignore.',
  },

  services: {
    slug: 'services',
    href: '/services/',
    menu_title: 'Services',
    menu_aria_label: 'Discover my services',
    title: 'Services',
    description: 'I work across cultural, educational, tourism, and public environments, including museums, exhibitions, archives, schools, universities, visitor centres, municipalities, and heritage sites.',
    cta_quote: 'How we design matters. Let’s think about it.',
  },
}

const projects = {
  cruquius_museum: {
    slug: 'cruquius-museum',
    href: '/projects/cruquius-museum/',
    menu_title: 'Cruquius Museum',
    aria_label: 'Explore the “Cruquius Museum” project',
    title: 'Cruquius Museum',
    description: 'An immersive look at Haarlemmermeer’s history and the world’s largest steam engine.',
    subtitle: 'Cruquius Museum, Cruquius (NL), 2020',
    subtitle_short: 'Cruquius Museum, Cruquius (NL)',
    label: 'Featured',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  family_exhibits: {
    slug: 'family-exhibits',
    href: '/projects/family-exhibits/',
    menu_title: 'Family Exhibits',
    menu_aria_label: 'Explore the “Family Exhibits” project',
    title: 'Family Exhibits',
    description: 'A multi-sensory family journey into Qatar’s heritage, shaped by play and discovery.',
    subtitle: 'National Museum of Qatar, Doha (QA), 2019',
    subtitle_short: 'National Museum of Qatar, Doha (QA)',
    label: 'Awarded',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  herman_boerhaave: {
    slug: 'herman-boerhaave',
    href: '/projects/herman-boerhaave/',
    menu_title: 'Herman Boerhaave',
    menu_aria_label: 'Explore the “Herman Boerhaave” project',
    title: 'Herman Boerhaave',
    description: 'A walk through the life and world of one of the most influential Dutch physicians.',
    subtitle: 'Rijksmuseum Boerhaave, Leiden (NL), 2018',
    subtitle_short: 'Rijksmuseum Boerhaave, Leiden (NL)',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  het_steen: {
    slug: 'het-steen',
    href: '/projects/het-steen/',
    menu_title: 'Het Steen',
    menu_aria_label: 'Explore the “Het Steen” project',
    title: 'Het Steen',
    description: 'A visitor center inside Antwerp’s oldest building, made of stories, people, and places.',
    subtitle: 'Visit Antwerp, Antwerp (BE), 2021',
    subtitle_short: 'Visit Antwerp, Antwerp (BE)',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  joh_enschede: {
    slug: 'joh-enschede',
    href: '/projects/joh-enschede/',
    menu_title: 'Joh. Enschedé',
    menu_aria_label: 'Explore the “Joh. Enschedé” project',
    title: 'Joh. Enschedé',
    description: 'Exploring the printers behind pages, banknotes, and type that shaped a nation.',
    subtitle: 'Noord-Hollands Archief, Haarlem (NL), 2019',
    subtitle_short: 'Noord-Hollands Archief, Haarlem (NL)',
    label: 'Awarded + Featured',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  living_planet: {
    slug: 'living-planet',
    href: '/projects/living-planet/',
    menu_title: 'Living Planet',
    menu_aria_label: 'Explore the “Living Planet” project',
    title: 'Living Planet',
    description: 'Understanding biodiversity and ecosystems through playful investigation.',
    subtitle: 'Museum of Natural Sciences, Brussels (BE), 2020',
    subtitle_short: 'Museum of Natural Sciences, Brussels (BE)',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  maker_park: {
    slug: 'maker-park',
    href: '/projects/maker-park/',
    menu_title: 'Maker Park',
    menu_aria_label: 'Explore the “Maker Park” project',
    title: 'Maker Park',
    description: 'A digital platform for STREAM education through informal learning and games.',
    subtitle: 'ilmi Science Discovery & Innovation Center, Riyadh (SA), Expected opening in 2026',
    subtitle_short: 'ilmi Science Discovery & Innovation Center, Riyadh (SA)',
    cta_quote: 'Explore the next project or drop me a message.',
  },

  prodemos: {
    slug: 'prodemos',
    href: '/projects/prodemos/',
    menu_title: 'ProDemos',
    menu_aria_label: 'Explore the “ProDemos” project',
    title: 'ProDemos',
    description: 'A GPS game where students propose, debate, and bring their own laws to life.',
    subtitle: 'ProDemos, The Hague (NL), 2021',
    subtitle_short: 'ProDemos, The Hague (NL)',
    cta_quote: 'Explore the next project or start a conversation.',
  },

  shifting_image: {
    slug: 'shifting-image',
    href: '/projects/shifting-image/',
    menu_title: 'Shifting Image',
    menu_aria_label: 'Explore the “Shifting Image” project',
    title: 'Shifting Image',
    description: 'An exhibition revealing the many perspectives surrounding Dutch colonial history.',
    subtitle: 'Mauritshuis, The Hague (NL), 2019',
    subtitle_short: 'Mauritshuis, The Hague (NL)',
    label: 'Awarded',
    cta_quote: 'Explore the next project or drop me a message.',
  },
}

const resources = {
  we_are_all_temporarily_able_yes_you_too: {
    slug: 'we-are-all-temporarily-able-yes-you-too',
    href: '/resources/we-are-all-temporarily-able-yes-you-too/',
    menu_title: 'We are all temporarily able. Yes, you too.',
    menu_aria_label: 'Read my “We are all temporarily able. Yes you too.” article',
    title: 'We are all temporarily able. Yes, you too.',
    title_with_markup: 'We are all temporarily able. <br/>Yes, you too.',
    description: 'Stop thinking of disability as something that happens to “other people”. Discover why we are all temporarily able and how changing our perspective on design and accessibility can build a world that works for everyone.',
    subtitle: 'Anna Nogaré | <time datetime="2026-05-13">13-05-2026</time> | <em>12 min</em>',
    cta_quote: 'The more we talk about it, the harder it gets to ignore.',
  },
}

const section_cards = {
  about: {
    href: '/about/',
    title: 'Learn more about me',
    image: 'misc/anna-dots_1x1',
  },

  contact: {
    href: '/contact/',
    title: 'Get in touch',
    image: 'misc/vintage-telephone_1x1',
  },

  manifesto: {
    href: '/manifesto/',
    title: 'Read Accessibility Manifesto',
    image: 'misc/wheelchair-sign_1x1',
  },

  projects: {
    href: '/projects/',
    title: 'Selected projects',
    image: 'projects/shifting-image/thumbnail_1x1',
  },

  resources: {
    href: '/resources/',
    title: 'Resources',
    subtitle: 'A collection of articles, opinions, thoughts, and reflections.',
  },

  services: {
    href: '/services/',
    title: 'Discover my services',
    image: 'misc/reviewing-blueprints_1x1',
  },
}

const section_text_cards = {
  manifesto: {
    href: '/manifesto/',
    title: 'Manifesto',
    subtitle: 'We are all temporarily able. Yes, you too. And once you see it, you can’t unsee it.',
  },

  resources: {
    href: '/resources/',
    title: 'Resources',
    subtitle: 'A collection of articles, opinions, thoughts, and reflections.',
  },

  services: {
    href: '/services/',
    title: 'Services',
    subtitle: 'Interpretive Concept <br/>Creative Leadership <br/>Accessibility Strategy',
  },
}

const project_cards = {
  living_planet: {
    href: '/projects/living-planet/',
    title: 'Living planet',
    subtitle: 'Museum of Natural Sciences, Brussels (BE)',
    image: 'projects/living-planet/thumbnail_1x1',
  },

  joh_enschede: {
    href: '/projects/joh-enschede/',
    title: 'Joh. Enschedé',
    subtitle: 'Noord-Hollands Archief, Haarlem (NL)',
    label: 'Awarded + Featured',
    image: 'projects/joh-enschede/thumbnail_1x1',
  },

  prodemos: {
    href: '/projects/prodemos/',
    title: 'ProDemos',
    subtitle: 'ProDemos, The Hague (NL)',
    image: 'projects/prodemos/thumbnail_1x1',
  },

  shifting_image: {
    href: '/projects/shifting-image/',
    title: 'Shifting Image',
    subtitle: 'Mauritshuis, The Hague (NL)',
    label: 'Awarded',
    image: 'projects/shifting-image/thumbnail_1x1',
  },

  cruquius_museum: {
    href: '/projects/cruquius-museum/',
    title: 'Cruquius museum',
    subtitle: 'Cruquius Museum, Cruquius (NL)',
    label: 'Featured',
    image: 'projects/cruquius-museum/thumbnail_1x1',
  },

  herman_boerhaave: {
    href: '/projects/herman-boerhaave/',
    title: 'Herman Boerhaave',
    subtitle: 'Rijksmuseum Boerhaave, Leiden (NL)',
    image: 'projects/herman-boerhaave/thumbnail_1x1',
  },

  makerpark: {
    href: '/projects/family-exhibits/',
    title: 'Family Exhibits',
    subtitle: 'National Museum of Qatar, Doha (QA)',
    label: 'Awarded',
    image: 'projects/family-exhibits/thumbnail_1x1',
  },

  het_steen: {
    href: '/projects/het-steen/',
    title: 'Het Steen',
    subtitle: 'Visit Antwerp, Antwerp (BE)',
    image: 'projects/het-steen/thumbnail_1x1',
  },

  maker_park: {
    href: '/projects/maker-park/',
    title: 'Maker park',
    subtitle: 'ilmi Science Discovery & Innovation Center, Riyadh (SA)',
    image: 'projects/maker-park/thumbnail_1x1',
  },
}

const resource_cards = {}

export default {
  base,
  socials,
  alts,
  sections,
  projects,
  resources,
  section_cards,
  section_text_cards,
  project_cards,
  resource_cards,
}
