name: NodeJS with Sonic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.14.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0

    - name: Build
      run: |
        corepack enable yarn
        yarn
        node sonic build
